Sprint 3/step 1
dlart/react-burger pull request #5
Opened 2023-04-14 17:32 UTC by dlart

2023-04-14 20:20 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Используете тег `form`
- Реализован механизм обновления токена
- Используете useMemo

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не авторизованный пользователь не должен иметь возможность оформить заказ
- По заданию в случае успешной отправки запроса восстановления пароля пользователь должен перенаправляться на маршрут `/reset-password`, сейчас этого не происходит, пользователь так и остается на странице `/forgot-password`.
- Авторизация сбрасывается при перезагрузке страницы
- После обновления токена необходимо повторять неудавшийся запрос из-за которого и запустился процесс обновления токена. Рекомендую создать функцию, которая будет принимать 2 аргумента - эндпоинт и опции запроса. В ней необходимо осуществлять запрос с опциями, если он не проходит из-за ошибки токена попытаться его обновить, после обновления опять повторить ранее неудавшийся запрос с опциями и свежим токеном.

**Можно лучше**
- Лучше дизейблить кнопку заказа если в конструкторе нет булок.
- Сейчас если запрос регистрации падает, то всё равно происходит редирект на главную страницу, желательно дожидаться ответа от сервера и в зависимости от него делать редирект или показывать сообщение об ошибке. 
- При регистрации сервер возвращает токены, так что юзера можно сразу авторизовать.
- При клике по ингредиенту должно открываться модальное окно, а отдельная страница при прямом переходе по ссылке. Сейчас открывается всегда модальное окно.


Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-14 20:20 UTC, andryxxa93 commented on src/components/app/App.tsx
> +          <Route path="/login" element={<LoginPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-04-14 20:20 UTC, andryxxa93 commented on src/pages/login-page/LoginPage.jsx
> +    if (isLoggedIn) {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-04-14 22:28 UTC, dlart commented
_Не авторизованный пользователь не должен иметь возможность оформить заказ_

**Поправил и добавил чтобы заказ нельзя было отправить если нет ингредиентов.**

_По заданию в случае успешной отправки запроса восстановления пароля пользователь должен перенаправляться на маршрут /reset-password, сейчас этого не происходит, пользователь так и остается на странице /forgot-password._

**Поправил.**

_Авторизация сбрасывается при перезагрузке страницы_

**Поправил**

_После обновления токена необходимо повторять неудавшийся запрос из-за которого и запустился процесс обновления токена. Рекомендую создать функцию, которая будет принимать 2 аргумента - эндпоинт и опции запроса. В ней необходимо осуществлять запрос с опциями, если он не проходит из-за ошибки токена попытаться его обновить, после обновления опять повторить ранее неудавшийся запрос с опциями и свежим токеном._

**Добавил функцию с запросом нового токена**

2023-04-14 22:28 UTC, dlart commented on src/components/app/App.tsx
> +          <Route path="/login" element={<LoginPage />} />
Сделано

2023-04-14 22:30 UTC, dlart commented on src/pages/login-page/LoginPage.jsx
> +    if (isLoggedIn) {
Сделал отдельный компонент

2023-04-15 13:16 UTC, andryxxa93 commented
**Можно лучше**
У вас метод getUser вызывается в 3 местах. App, конструктор и профиль. Можно убрать из конструктора, иначе много дубликатов запросов в консоли.

2023-04-15 13:22 UTC, andryxxa93 commented
**Необходимо исправить**
Токен успешно обновляется, но после обновления повторный запрос не проходит. Дело в том, что в хедере у вас сразу два токена. Причина этого в том, что в одном месте вы пишите `Authorization` с заглавной буквы, а в другом со строчной. 

<img width="691" alt="Снимок экрана 2023-04-15 в 16 17 53" src="https://user-images.githubusercontent.com/60173362/232226258-a3a637c6-7adf-4c5d-bb28-435d48aaa0c0.png">

2023-04-16 08:18 UTC, dlart commented
getUser - оставил вызов в App
Authorization - Привел к единому виду "Authorization"

2023-04-16 19:37 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-24 12:16 UTC, merged