sprint-4/step-1
dlart/react-burger pull request #6
Opened 2023-04-27 08:51 UTC by dlart

2023-04-27 09:45 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Редкое использование `any`
- Хорошая типизация компонентов и функций

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Файл `ResetPasswordPage` имеет расширение - `jsx`
- Необходимо так же типизировать файлы в директории `utils`  
- В проекте много использований ts-ignore от которых можно отказаться. В комментариях приведены примеры как это сделать, исправьте во всех подобных местах.

Более подробно описание проблемы смотрите комментарии в pull request.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-27 09:45 UTC, andryxxa93 commented on src/pages/profile-page/ProfilePage.tsx
>      setForm({
**Необходимо исправить**
Тут можно избавиться от `ts-ignore` так - 

`  function onFormChange(event: ChangeEvent<{name: string, value: string}>): void {`

2023-04-27 09:45 UTC, andryxxa93 commented on src/components/routing-modal/RoutingModal.tsx
> +          /** @ts-ignore */
**Необходимо исправить**
Тут можно избавиться от ts-ignore если добавить в интерфейс модалки поле `children` - с 18 версии реакта `children` больше не входят в тип `React.FC ` поэтому их надо добавлять руками.

```
interface IModalProps {
    onClose?: () => void;
    title: string;
    children: ReactNode
}
```

2023-04-27 09:45 UTC, andryxxa93 commented on src/components/app-header/AppHeader.tsx
> +              /** @ts-ignore */
**Необходимо исправить**
В сообщении об ошибке указано, что 
`Type 'null' is not assignable to type 'string | undefined'.`
Т.е. вам чтобы избавиться от ошибки надо всего лишь вместо `null` поставить `undefined`

2023-04-27 09:45 UTC, andryxxa93 commented on src/components/protected-route/ProtectedRoute.tsx
> +// @ts-ignore
**Необходимо исправить**
Тут и во всех подобных местах можно починить вот так - `export const ProtectedRoute: FC<{children: any}>`

2023-04-27 09:45 UTC, andryxxa93 commented on src/components/burger-constructor-ingredient/BurgerConstructorIngredient.tsx
>          handleClose={() => {handleItemDelete(ingredient._id, index)}}
**Необходимо исправить**
Тут надо просто поменять тип у функции `handleItemDelete ` со `string` на `number`

2023-04-27 09:45 UTC, andryxxa93 commented on src/components/modal/Modal.tsx
> +      /** @ts-ignore */
**Необходимо исправить**
Тут можно скастовать `modalRoot ` напрямую к нужному типу  и ошибки не будет
`const modalRoot = document.getElementById('modal-root') as Element;`

2023-04-27 11:26 UTC, dlart commented on src/pages/profile-page/ProfilePage.tsx
>      setForm({
Ок

2023-04-27 11:26 UTC, dlart commented on src/components/routing-modal/RoutingModal.tsx
> +          /** @ts-ignore */
Ок

2023-04-27 11:27 UTC, dlart commented on src/components/app-header/AppHeader.tsx
> +              /** @ts-ignore */
Ок

2023-04-27 11:27 UTC, dlart commented on src/components/protected-route/ProtectedRoute.tsx
> +// @ts-ignore
Ок

2023-04-27 11:27 UTC, dlart commented on src/components/burger-constructor-ingredient/BurgerConstructorIngredient.tsx
>          handleClose={() => {handleItemDelete(ingredient._id, index)}}
Ок

2023-04-27 11:27 UTC, dlart commented on src/components/modal/Modal.tsx
> +      /** @ts-ignore */
Ок

2023-04-28 04:50 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-28 08:24 UTC, merged